pekko {
  actor {
    provider = "cluster"

    serializers {
      jackson-json = "org.apache.pekko.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-bindings {
      "com.example.lab7.sdn.MySerializable" = jackson-json
    }
  }

  remote {
    artery {
      canonical {

        hostname = "localhost"
        hostname = ${?PEKKO_HOSTNAME}
        port = 2551
      }
    }
  }

  cluster {

    seed-nodes = ["pekko://SDNSystem@controller:2551"]
  }
}